name: Tony Avantia
favicon: null
layout_spectrum: 0.7522941918577999
typography_spectrum: 0.9700480971951038
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.1543210055679083
  lightness: 0.5146574380341917
  saturation: 0.15379067487083375
  rhythmicContrast: 0.7603067841846496
purpose: []
